### ISSUE TITLE
ios | when the screen locked display this statment "some error occured please try reconnect ..." 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#43]
ios | when the phone screen is locked display this statement "some error occurred please try to reconnect ..."  and I follow the structure on the popup by typing restart and nothing happen I have to click on the arrow back the continue conversation 
Steps:

1. open the app
2. fill out the form
3. leave the app running in the background for 30 sec 
4. a note is displayed in popup with: "some error occurred please try to reconnect ..." 
     Or
5. leave the app till the phone screen lock
6. a note is displayed in popup with: "some error occurred please try to reconnect ..." 

**Expected Result:**
can continue the conversation normal

**Actual Result**
I follow the structure on the popup by typing restart and nothing happen I have to click on the arrow back the continue conversation 
![274758821_1399300067167575_3269837480097514128_n](https://user-images.githubusercontent.com/96580545/156408693-baa11914-7566-4e6c-be84-7226abfaa2ba.jpg)

https://user-images.githubusercontent.com/96580545/156409026-9020168a-59e1-46ad-aeac-db41825e457f.mp4

**Comment by technicalbirdVayuz** [comment]
Fixed in the last shared build

**Comment by abanoubBC** [comment]
@technicalbirdVayuz still the same issue

https://user-images.githubusercontent.com/96580545/157211772-0a1007dd-f8e5-4445-8b3f-e6fd2a2fd94a.mp4

**Comment by technicalbirdVayuz** [comment]
Ok, we will remove the popup when it's connected with the Agent (as it is not required)

You can check this case as when the user is not connecting to the agent, You will receive a Popup, post-confirmation there will it will reconnect again.



https://user-images.githubusercontent.com/18699624/157219649-da3a2d01-efc8-4349-aee5-c77679e5f8b8.mp4
